### ISSUE TITLE
数据集缺少mosei_dict/train_valid_test.pt

### ISSUE THREAD

**Issue by Zhudogsi** [MANLP-suda/HHMPN#10]
您好，感谢您代码的开源，您提供了mosei_emotion_aligned_60.pkl，但是它不能用于运行报错如下：
Traceback (most recent call last):
  File "main.py", line 129, in <module>
    main(opt)
  File "main.py", line 49, in main
    train_data,valid_data,test_data,label_adj_matrix,opt = process_data(data,opt)
  File "/HHMPN-main/HHMPN/utils/data_loader.py", line 69, in process_data
    label_adj_matrix = get_matrix(data['train']['tgt'],data['dict']['tgt'],t=0.2)
KeyError: 'tgt'
期待您的回复

**Comment by MANLP-suda** [comment]
可以先pickle加载后，查看data.keys() 是否有对应。
